### ISSUE TITLE
Error in database generation

### ISSUE THREAD

**Issue by ufuomababatunde** [liaoherui/VirStrain#11]
Hello. I tried constructing a database with 98 sequences using the following command:

`virstrain_build -i VOI_RepresentativeGenomes_CodonAligned_2022-08-15.fasta -d DB_custom -s 1`

But it's taking too long to finish so I used VirStrain_build.py after doing the git installation as shown below:
`python VirStrain_build.py -i VOI_RepresentativeGenomes_CodonAligned_2022-08-15.fasta -d DB_custom_gitbuild -s`

However, I encountered the error below:
```
Kmer POS-Snp file done! Start generating matrix.                                                              
Traceback (most recent call last):                                                                            
  File "/home/user/VirStrain/bin/S2_remove_redundant_For_Me.py", line 77, in <module>           
    o2.write('\t'+final[0]+'\t*\t'+str(ds2id[final[0]])+'\n')                                                 
IndexError: list index out of range                                                                           
Smartmatch is experimental at /home/user/VirStrain/bin/aln2cluster-overlap-kmer-withd.pl line 216.                                                                                                            
Use of uninitialized value $char in pattern match (m//) at /home/user/VirStrain/bin/aln2cluster-overlap-kmer-withd.pl line 81.                                                                                
Use of uninitialized value $char in pattern match (m//) at /home/user/VirStrain/bin/aln2cluster-overlap-kmer-withd.pl line 81.                                                                                
Smartmatch is experimental at /home/user/VirStrain/bin/aln2cluster-overlap-kmer-withd.pl line 216.                                                                                                            
Use of uninitialized value $char in pattern match (m//) at /home/user/VirStrain/bin/aln2cluster-overlap-kmer-withd.pl line 81.                                                                                
Use of uninitialized value $char in pattern match (m//) at /home/user/VirStrain/bin/aln2cluster-overlap-kmer-withd.pl line 81.                                                                                
Use of uninitialized value $char in pattern match (m//) at /home/user/VirStrain/bin/aln2cluster-overlap-kmer-withd.pl line 81.                                                                                
Smartmatch is experimental at /home/user/VirStrain/bin/aln2cluster-overlap-kmer-withd.pl line 216.
```

**Comment by liaoherui** [comment]
Hi, can you try to remove “-s “ parameter and run VirStrain again? By the way, -s must follow a value (0-1) or the program will return error. Thanks!

**Comment by ufuomababatunde** [comment]
Hello.
I tried removing the "-s" parameter and I still got this error.

```
Kmer POS-Snp file done! Start generating matrix.                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                                 
  File "bin/S2_remove_redundant_For_Me.py", line 77, in <module>                                                                                                                                                                   
    o2.write('\t'+final[0]+'\t*\t'+str(ds2id[final[0]])+'\n')                                                                                                                                                                      
IndexError: list index out of range
```

**Comment by liaoherui** [comment]
Hi, it's a little hard to debug without the dataset. Would you mind sending all reference genomes or partial genomes (like 10 or 20 genomes) you used to build the database to me to test the program? Thanks a lot!

**Comment by ufuomababatunde** [comment]
Thank you for your quick response.
I used this [msa file](https://drive.google.com/file/d/12AL5ouQJEaIl3H0RFgGx4ezJp8E7suED/view?usp=sharing).

**Comment by liaoherui** [comment]
Hi, thanks for your test file!
I have checked your file and found "," is contained in the headline of some genomes. Once I remove these ",", the program can run normally. One demo file (generated from your test file) is attached for your test.
[new_VOI_test.zip](https://github.com/liaoherui/VirStrain/files/10533399/new_VOI_test.zip)

**Comment by ufuomababatunde** [comment]
Wow! It's okay now.

Thank you very much.
I'll make sure to take note of that next time.
